openapi: 3.0.1
info:
  description: "Streamus server REST Api"
  version: "1.0.0"
  title: "Streamus"
  contact:
    email: "henrik.akesson@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /artists:
    get:
      tags:
      - artists
      summary: Get all artists
      operationId: getAllArtists
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
              example:
                - id: 136
                  name: Pink Floyd
                  albums:
                  - id: 118
                    name: Animals
                    createdAt: 1591601762518
                    updatedAt: 1591601762542
                    tracks:
                    - id: 1240
                      name: Pigs on the Wing (Part 1)
                      duration: 100
                      trackNumber: 1
                    - id: 1241
                      name: Dogs
                      duration: 100
                      trackNumber: 2
                    - id: 1242
                      name: Pigs (Three Different Ones)
                      duration: 100
                      trackNumber: 3
                    - id: 1243
                      name: Sheep
                      duration: 100
                      trackNumber: 4
                    - id: 1244
                      name: Pigs on the Wing (Part 2)
                      duration: 100
                      trackNumber: 5
                  members:
                    - id: 182
                      albums: []
                      firstName: Syd
                      lastName: Barrett
                      dateOfBirth: -756954000000
                      createdAt: 1591605887479
                      updatedAt: 1591605887479
                      from: -157770000000
                      to: -31626000000
                    - id: 185
                      albums: []
                      firstName: Roger
                      lastName: Waters
                      dateOfBirth: -830656800000
                      createdAt: 1591605887488
                      updatedAt: 1591605887488
                - id: 185
                  albums: []
                  firstName: Roger
                  lastName: Waters
                  dateOfBirth: -830656800000
                  createdAt: 1591605887488
                  updatedAt: 1591605887488
                - id: 182
                  albums: []
                  firstName: Syd
                  lastName: Barrett
                  dateOfBirth: -756954000000
                  createdAt: 1591605887479
                  updatedAt: 1591605887479
                  from: -157770000000
                  to: -31626000000
  /film/{id}:
    get:
      tags:
        - films
      summary: Find film by id
      operationId: getFilmById
      parameters: 
        - name: id
          in: path
          description: Id of requested film
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
              example: 
                id: 1230
                name: Parasite
                duration: 132
        404:
          description: Film not found
          content: {}
  /films:
    get:
      tags:
      - films
      summary: Get all films
      operationId: getAllFilms
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
              example:
                - id: 1230
                  name: Parasite
                  duration: 132
    post:
      tags:
        - films
      summary: "Add a new film"
      operationId: "addFilm"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: upload successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  duration:
                    type: integer
        400:
          description: Upload unsuccessful
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
components:
  schemas:
    Film:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
    Track:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
        trackNumber:
          type: "integer"
    Album:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
        tracks:
          type: "array"
          items:
            $ref: '#/components/schemas/Track'
    Person:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        dateOfBirth: 
          type: "integer"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
    Musician:
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: "object"
          properties:
            name: 
              type: "string"
      properties:
        albums:
          type: "array"
          items:
            $ref: '#/components/schemas/Album'
    Band:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        members:
          type: "array"
          items:
            $ref: '#/components/schemas/Musician'
        albums:
          type: "array"
          items:
            $ref: '#/components/schemas/Album'
    Artist:
      anyOf:
        - $ref: '#/components/schemas/Band'
        - $ref: '#/components/schemas/Musician'