openapi: 3.0.1
info:
  description: "Streamus server REST Api"
  version: "1.0.0"
  title: "Streamus"
  contact:
    email: "henrik.akesson@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /artists:
    get:
      tags:
      - Artists
      summary: Get all artists
      operationId: getAllArtists
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
              example:
                - id: 136
                  name: Pink Floyd
                  albums:
                  - 118
                  members:
                    - id: 182
                      albums: []
                      firstName: Syd
                      lastName: Barrett
                      dateOfBirth: '1946-01-06'
                      createdAt: '2020-06-08 22:13:02'
                      updatedAt: '2020-06-08 22:13:02'
                      from: '1965-01-01'
                      to: '1968-01-01'
                    - id: 185
                      albums: []
                      firstName: Roger
                      lastName: Waters
                      dateOfBirth: '1943-09-06'
                      createdAt: '2020-06-08 22:12:58'
                      updatedAt: '2020-06-08 22:12:58'
                      from: '1965-01-01'
                      to: '1985-01-01'
                - id: 185
                  albums: []
                  firstName: Roger
                  lastName: Waters
                  dateOfBirth: '1943-09-06'
                  createdAt: '2020-06-08 22:12:58'
                  updatedAt: '2020-06-08 22:12:58'
                - id: 182
                  albums: []
                  firstName: Syd
                  lastName: Barrett
                  dateOfBirth: '1946-01-06'
                  createdAt: '2020-06-08 22:13:02'
                  updatedAt: '2020-06-08 22:13:02'
  /artist/{id}:
    get:
      tags:
        - Artists
      summary: Find artist by id
      operationId: getArtistById
      parameters: 
        - name: id
          in: path
          description: Id of requested artist
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
              example: 
                - id: 182
                  albums: []
                  firstName: Syd
                  lastName: Barrett
                  dateOfBirth: '1946-01-06'
                  createdAt: '2020-06-13 14:22:43'
                  updatedAt: '2020-06-13 14:22:43'
        404:
          description: Film not found
          content: {}
    delete:
      tags:
        - Artists
      summary: Delete an artist (band or musician) by id
      operationId: deleteArtistById
      parameters:
        - name: id
          in: path
          description: Id of artist to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
        404:
          description: Artist not found

  /band:
    post:
      tags:
        - Artists
      summary:
        Create a new Band
      operationId: createBand
      requestBody:
        description: Data of band to create
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
              example:
                id: 1230
                name: "Emperor"
                albums: []
        400:
          description: Operation failed
  /musician:
    post:
      tags:
        - Artists
      summary: Create a new musician
      operationId: createMusician
      requestBody:
        description: 
          Data of Musician to create.
          If name is not defined, either person.id should be a valid person id or
          person.firstName and person.lastName should be valid.
        content:
          application/json:
            schema:
              type: object
              properties:
                person:
                  type: object
                  properties:
                    id:
                      type: integer
                    firstName:
                      type: string
                    lastName:
                      type: string
                    dateOfBirth:
                      type: integer
                name:
                  type: string
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musician'
              example:
                id: 1230
                name: "Test"
        400:
          description: Operation failed
  /band/{id}/members:
    post:
      tags:
        - Artists
      summary: Add a member to a band
      operationId: addMember
      parameters: 
        - name: id
          in: path
          description: Id of band
          required: true
          schema:
            type: integer
      requestBody:
        description: Data of musician to add. Either a musician id, an object containing a person with an id, or a musician.
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Musician'
                - type: object
                  properties:
                    person:
                      oneOf:
                        - $ref: '#/components/schemas/Person'
                        - type: object
                          properties:
                            id: 
                              type: integer
                - properties:
                    musicianId:
                      type: integer
              properties:
                from:
                  type: string
                to:
                  type: string
              example: 
                musicianId: 142
                from: '2000-01-01'
                to: '2010-01-01'
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
        400:
          description: Operation unsuccessful. Usually due to overlapping memberships of a musician to the same band.
  /albums:
    post:
      tags:
        - Albums
      summary: Create a new album
      operationId: createAlbum
      requestBody:
        description: 
          Data of Album to create.
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                releaseDate:
                  type: string
                artistIds:
                  type: array
                  items:
                    type: integer
                tracks:
                  type: array
                  items:
                    type: object
                    properties:
                      trackNumber:
                        type: integer
                      songId:
                        type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        400:
          description: Operation failed, invalid data. For example, invalid artist or song ids, invalid track numbers (should be 1, 2, ..., n)
  /album/{id}:
    get:
      tags:
        - Albums
      summary: Find an album by id
      operationId: getAlbumById
      parameters: 
        - name: id
          in: path
          description: Id of requested album
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        404:
          description: Not found
    delete:
      tags:
        - Albums
      summary: Delete an album by id
      operationId: deleteAlbumById
      parameters:
        - name: id
          in: path
          description: Id of album to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
        404:
          description: Album not found
  # FILMS
  /film/{id}:
    get:
      tags:
        - Films
      summary: Find film by id
      operationId: getFilmById
      parameters: 
        - name: id
          in: path
          description: Id of requested film
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
              example: 
                id: 1230
                name: Parasite
                duration: 132
        404:
          description: Film not found
          content: {}
    delete:
      tags:
        - Films
      summary: Delete a film by id
      operationId: deleteFilmById
      parameters:
        - name: id
          in: path
          description: Id of film to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
        404:
          description: Film not found
  /film/{id}/stream:
    get:
      tags:
        - Films
      summary: Get a stream for a film
      operationId: streamFilm
      parameters: 
        - name: id
          in: path
          description: Id of requested film
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            video/mp4:
              schema:
                type: string
                format: binary
  /films:
    get:
      tags:
      - Films
      summary: Get all films
      operationId: getAllFilms
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
              example:
                - id: 1230
                  name: Parasite
                  duration: 132
    post:
      tags:
        - Films
      summary: "Add a new film"
      operationId: "addFilm"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: upload successful
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Film'
              example:
                id: 1230
                name: Parasite
                duration: 132
        400:
          description: Upload unsuccessful
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string

  /song/{id}:
    delete:
      tags:
        - Songs
      summary: Delete a song by id
      operationId: deleteSongById
      parameters:
        - name: id
          in: path
          description: Id of song to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
        404:
          description: Song not found
  /songplaylist:
    post:
      tags:
        - SongPlaylists
      summary: Create a new song playlist
      operationId: createSongPlaylist
      requestBody:
        description:
          Data of Song playlist to create.
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                releaseDate:
                  type: string
                artistIds:
                  type: array
                  items:
                    type: integer
                tracks:
                  type: array
                  items:
                    type: object
                    properties:
                      trackNumber:
                        type: integer
                      songId:
                        type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongPlaylist'
        400:
          description: Operation failed, invalid data. For example, invalid artist or song ids, invalid track numbers (should be 1, 2, ..., n)
  /songplaylist/{id}:
    get:
      tags:
        - SongPlaylists
      summary: Find an song playlist by id
      operationId: getSongPlaylistById
      parameters: 
        - name: id
          in: path
          description: Id of requested song playlist
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongPlaylist'
        404:
          description: Not found
    put:
      tags:
        - SongPlaylists
      summary: Add a track to a playlist. If track number is greater than the greatest track number + 1, it is 
               by default set as greatest track number + 1
      operationId: addTrackToPlaylist
      parameters: 
        - name: id
          in: path
          description: Id of requested song playlist
          required: true
          schema:
            type: integer
      requestBody:
        description: Track to add
        content:
          application/json:
            schema:
              type: "object"
              properties:
                trackNumber:
                  type: integer
                songId:
                  type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongPlaylist'
        400:
          description: Track number <= 0 or > current size
        404:
          description: Not found. Either SongPlaylist or Song does not exist
    delete:
      tags:
        - SongPlaylists
      summary: Delete an song playlist by id
      operationId: deleteSongPlaylistById
      parameters:
        - name: id
          in: path
          description: Id of song playlist to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
        404:
          description: SongPlaylist not found
  /songplaylist/{songPlaylistId}/{songId}:
    post:
      tags:
        - SongPlaylists
      summary: Add a song at the end of the playlist
      operationId: addSongToPlaylist
      parameters:
        - name: songPlaylistId
          in: path
          description: Id of requested song playlist
          required: true
          schema:
            type: integer
        - name: songId
          in: path
          description: Id of requested song
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongPlaylist'
        404:
          description: Not found
        400:
          description: Bad request. For example if song is already present in playlist.

components:
  schemas:
    Film:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
    Track:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
        trackNumber:
          type: "integer"
    Album:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
        tracks:
          type: "array"
          items:
            $ref: '#/components/schemas/Track'
        artists:
          type: "array"
          items:
            $ref: '#/components/schemas/Artist'
    SongPlaylist:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
        tracks:
          type: "array"
          items:
            $ref: '#/components/schemas/Track'
        user:
          type: "object"
          items:
            $ref: '#/components/schemas/User'
    Person:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        dateOfBirth: 
          type: "integer"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
    User:
      type: "object"
      properties:
        email:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        dateOfBirth: 
          type: "integer"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
    Musician:
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: "object"
          properties:
            id:
              type: integer
            name:
              type: "string"
      properties:
        albums:
          type: "array"
          items:
            type: integer
    Band:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        members:
          type: "array"
          items:
            $ref: '#/components/schemas/Member'
        albums:
          type: "array"
          items:
            type: integer
    Member:
      allOf:
        - $ref: '#/components/schemas/Musician'
        - type: "object"
          properties:
            from: 
              type: string
            to: 
              type: string
    Artist:
      anyOf:
        - $ref: '#/components/schemas/Band'
        - $ref: '#/components/schemas/Musician'