openapi: 3.0.1
info:
  description: "Streamus server REST Api"
  version: "1.0.0"
  title: "Streamus"
  contact:
    email: "henrik.akesson@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
components:
  schemas:
    Film:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
    Track:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        duration:
          type: "integer"
        trackNumber:
          type: "integer"
    Album:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
        tracks:
          type: "array"
          items:
            $ref: '#/components/schemas/Track'
    Person:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        dateOfBirth: 
          type: "integer"
        createdAt:
          type: "integer"
        updatedAt:
          type: "integer"
    Musician:
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: "object"
          properties:
            name: 
              type: "string"
      properties:
        albums:
          type: "array"
          items:
            $ref: '#/components/schemas/Album'
    Band:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        members:
          type: "array"
          items:
            $ref: '#/components/schemas/Musician'
        albums:
          type: "array"
          items:
            $ref: '#/components/schemas/Album'